
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 07 19:48:29 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.si110350;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 17;
  public static final int LE_EQU = 30;
  public static final int RIGHT_BRACKET = 40;
  public static final int CONST = 10;
  public static final int RIGHT_SQUARE_BRACKET = 42;
  public static final int GREATER = 27;
  public static final int SEMI_COMMA = 36;
  public static final int MINUS = 21;
  public static final int STR_CONST = 19;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int INC = 34;
  public static final int DIV = 23;
  public static final int LESSER = 29;
  public static final int PLUS = 20;
  public static final int LEFT_CURLY_BRACKET = 43;
  public static final int IF = 5;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 33;
  public static final int LEFT_SQUARE_BRACKET = 41;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 15;
  public static final int MOD = 24;
  public static final int BREAK = 3;
  public static final int IDENT = 16;
  public static final int VOID = 12;
  public static final int ELSE = 6;
  public static final int L_EQUAL = 25;
  public static final int READ = 11;
  public static final int WHILE = 13;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int GR_EQU = 28;
  public static final int BOOL_CONST = 18;
  public static final int DEC = 35;
  public static final int RIGHT_CURLY_BRACKET = 44;
  public static final int LEFT_BRACKET = 39;
  public static final int L_NEQUAL = 26;
  public static final int PRINT = 8;
}

